name: Build and Release APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APK
        run: go run ./src/main.go --token="${{ secrets.GITHUB_TOKEN }}"

      - name: Get APK version info
        id: apk-info
        uses: hkusu/apk-info-action@v1
        with:
          apk-path: 'app-debug.apk'

      - name: Debug APK Version
        run: echo "APK version name ${{ steps.apk-info.outputs.version-name }}"

      - name: Get latest tag
        id: get-latest-tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Compare and delete tag if exists
        run: |
          current_tag="v1.0.0"  # Replace this with dynamic tag version or from APK info
          if [ "$current_tag" == "$latest_tag" ]; then
            echo "Tag $current_tag already exists. Deleting it..."
            git tag -d $current_tag || true
            git push origin :refs/tags/$current_tag || true
          else
            echo "Tag $current_tag does not exist. Proceeding to create a new tag."
          fi

      - name: Create and push new tag
        run: |
          git tag $current_tag
          git push origin $current_tag

      - name: Push changes to GitHub
        run: |
          git config --global user.email "apk-artifacts-downloader@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Update APK to $current_tag"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
